### ISSUE TITLE
How to handle offset parameter for figure and marginfigure

### ISSUE THREAD

**Issue by mikson** [Synthetica9/tufte-pandoc#18]
Thanks for a nice template/scaffold! A question, how can I / should I handle the _offset_ parameter for figures and marginfigures? It would be convenient to be able to adjust vertical offset somehow. I refer to the offsets like `1.0in` below:

    \begin{marginfigure}[1.0in]

**Comment by Synthetica9** [comment]
You could create a new environment based on `marginfigure` if you're gonna use it more often [(see here for example)](https://github.com/Synthetica9/tufte-pandoc/blob/master/header.tex#L8), which you can then assign to a new name in https://github.com/Synthetica9/tufte-pandoc/blob/master/meta.yaml#L24. 

For your specific situation, you might just be able to use `\vspace{1in}` directly at the top of your figure?

**Comment by mikson** [comment]
Thanks for a swift answer and confirming my hunch! I realized the \vspace idea soon after posting my comment and did some regex magic to get it spread out in my 150 places where it was needed. 👍
